### ISSUE TITLE
practice request may fail on new or modified decks

### ISSUE THREAD

**Issue by marcsolomon** [Capstone-Team-3/open-fluency#115]
symptom - when requesting practice, the user gets the null pointer error, or some cards are missing from the practice list
cause - the flashcard_info rows are not always defined for a user
possible fix - create any missing flashcard_info rows at the point that a user requests a practice session

case 1
- instructor creates a deck
- student opens the deck directly from "search for deck" (not add to my decks)
- click on practice -> null pointer

case 2
- student already has a deck in "my decks"
- instructor adds cards to the deck
- student does not see the new cards when practicing this deck

**Comment by beacrett** [comment]
I'll take a look at both.  We need to use the service calls when ever people are adding / accessing decks - they take care of all the above.  There is a function in flashcardInfoService that makes sure a card is added to practice queues for everyone whom added the deck.

**Comment by beacrett** [comment]
Case 1 is fixed.  Case 2 - I can't recreate the bug.  I added a new card as an instructor, refreshed my student window and saw it right away and as the first card in Practice (if you use the linear algo for a deck a new card added will always be on the top of the deck - set it up like that in part to facilitate testing)

**Comment by marcsolomon** [comment]
problem seems fixed.  another one bites the dust
