### ISSUE TITLE
kanji selected for our sample decks needs cleanup

### ISSUE THREAD

**Issue by marcsolomon** [Capstone-Team-3/open-fluency#116]
The redundancy in the current lists is confusing for Practice and Quizzes.
Will a change at this point affect the scripted functional testing?

**Comment by marcsolomon** [comment]
I'll fix this on the release of the persistent database file

**Comment by nicoten** [comment]
Marc, is this fixed?

**Comment by marcsolomon** [comment]
Yes, fixed.  I'll close the ticket.  --

---

Marc Solomon

marcsolomon@rcn.com

**Comment by marcsolomon** [comment]
fixed with the release of the persistent database.  closing the ticket.
