### ISSUE TITLE
Researcher Data is not actually comma-separated (??) - appears to be tab/space separated

### ISSUE THREAD

**Issue by kalongthewires** [Capstone-Team-3/open-fluency#129]
Example: 
"DeckID"    "UserID"    "Title" "Description"   "Algorithm" "FocalLanguageID"   "BaseLanguage"
"1" "2" "Restaurant"    "Words that I would use in a restaurant context"    "Linear-With-Shuffle"   "1" "English"

**Comment by beacrett** [comment]
Yep - tab separated - it was mentioned in the last meeting.  There are too
many phrases etc that contain commas to use them as separators.  Tabs are
the #2 'default' separator for .csv files and most analytics software (R,
Excel etc) will recognize it by default.  It will be in the data
descriptions.

**Comment by beacrett** [comment]
BTW - like the styling on research dashboard.  I'll add more detain to the
download descriptions.

**Comment by kalongthewires** [comment]
Oh man - now I totally remember that being brought up in the meeting and me being all for it. Alright, let me just quietly close this now ...

**Comment by beacrett** [comment]
lol - you've got a great sense of humor by the way
