### ISSUE TITLE
Researcher Data - IDs with unknown meaning

### ISSUE THREAD

**Issue by kalongthewires** [Capstone-Team-3/open-fluency#130]
Example: TestedElement columns (which are in many of the CSV files) contain numbers and I don't see any place where the researcher could determine/map the meanings for those numbers.

Another Example: in AnswerData.csv, the AnswerStatus and AnswerCorrectly columns  (looks like the latter many be a 0=false, 1=true)

**Comment by beacrett** [comment]
I'll cover it in Data Download Definitions - I'm going to make a data
details page that is linked from the dashboard that covers what is in every
data set.  You are correct - AnswerCorrectly is binary - there are a few
binary fields.  I'll define what answer status and TestedElement are in
that page.

**Comment by nicoten** [comment]
For the TestedElement column, you can get the actual word from the array in Constants.CARD_ELEMENTS and access it by the index that is there now. Does that make sense?

**Comment by kalongthewires** [comment]
I like the idea of having tested elements spelled out explicitly. (And spelling out any other column data which can be converted to from a number/ID to something more meaningful easily.) 

Also, I styled the dashboard and added some initial descriptions of the different data sets. You may be able to just add onto those so take a look and see what you think. I think avoiding extra clicks to additional pages is better for usability but definitely open to other ideas/opinions.

**Comment by beacrett** [comment]
I had everything spelled out before (its a quick change).  I swapped it to
ids where ever possible though for a reason -> all analytics packages
provide a SQL like or easy to use methods to link - join - 'apply'
functions across data tables (even excel).  Speaking as someone who's been
in analytics for the past decade - id values are easy to work with and tend
to consistency, string values are poor linking fields and tend to
facilitate incorrect joins.  If people feel really strongly about it, I can
change things, but fwiw I think using id fields better supports researchers.

**Comment by kalongthewires** [comment]
Fair enough - I feel like I remember us having this discussion before too. No brains left. I don't have much data processing experience (except really annoying ones from Visualizations class), so I bow to your superior experience level.

**Comment by beacrett** [comment]
No worries - we didn't really discuss this stuff.  I think I'll take your
idea to change the 'ElementTested' field to text - I left that one numeric
before just because we hadn't fixed down the practice elements - there is
only 3 options after all.

**Comment by beacrett** [comment]
think we've covered this  closing, but I'll still take a second look tomorrow
