### ISSUE TITLE
Audio doesn't show if create a flashcard with audio

### ISSUE THREAD

**Issue by kalongthewires** [Capstone-Team-3/open-fluency#131]
Noticed when logged in as researcher

**Comment by beacrett** [comment]
I noticed that audio is hidden when pronunciation is hidden - that's not
the problem by chance?

**Comment by beacrett** [comment]
Its working right now in all modes as far as I can tell

**Comment by kalongthewires** [comment]
It works in all practice modes, just not on the deck/show page.

Thanks for the idea! I'll check the pronunciations since I did move the audio. Could be something related to that.
