### ISSUE TITLE
FlashCard View helpers (default deck id)

### ISSUE THREAD

**Issue by beacrett** [Capstone-Team-3/open-fluency#2]
Update the view so that default deck is the deck you were routed here from (if coming from a deck).  Will also make image search auto populate when a meaning is chosen - when the search is added.

**Comment by nicoten** [comment]
Just leaving a comment to explain a bit more. This is, when you want to create a Flashcard, the Deck that the flashcard is going to should be pre-populated with the Deck that you're coming from.

**Comment by beacrett** [comment]
fixed a couple days ago
