### ISSUE TITLE
create flashcard - system error if required fields not entered

### ISSUE THREAD

**Issue by marcsolomon** [Capstone-Team-3/open-fluency#21]
create flashcard - system error if required fields not entered
impact: low-medium
location: select deck -> -> specify flashcard details
if the values for pronunciation or deck are not provided, the system throws the Error 500 page. user continues with browser back arrow
possible solution: provide default values for both pronunciation and deck

**Comment by nicoten** [comment]
I made the selects have the default value as the first item in the list instead of being null
