### ISSUE TITLE
practice flashcards - need navigation out of practice page

### ISSUE THREAD

**Issue by marcsolomon** [Capstone-Team-3/open-fluency#23]
practice flashcards - need navigation out of practice page
impact: low
location: select deck -> Practice Flashcards
the practice page needs a "return to deck" button, or breadcrumbs

**Comment by nicoten** [comment]
This will be solved once we add breadcrums per issue:
https://github.com/Capstone-Team-3/open-fluency/issues/7

Closing since it's duplicate.
