### ISSUE TITLE
Practice Flashcards from Chapter - Images missing, [ ] brackets showing

### ISSUE THREAD

**Issue by marcsolomon** [Capstone-Team-3/open-fluency#24]
Practice Flashcards from Chapter - Images missing, [ ] brackets showing
Location: Course Search -> select Course -> select Chapter -> Practice Flashcards
1) still shows [ ] around all data items
2) image region is on the card, but empty
3) navigation through the cards works correctly

**Comment by nicoten** [comment]
Just removed the [ ] from the practice flashcard on chapters

**Comment by nicoten** [comment]
Marc, can you create a separate issue for 2) ?

**Comment by marcsolomon** [comment]
Will do.  --

---

Marc Solomon – CAADS Practice, Administrative Technology Services – Harvard University – 617-495-5553
