### ISSUE TITLE
Practice Flashcards from Deck or Chapter - Shows only the first card in custom deck

### ISSUE THREAD

**Issue by marcsolomon** [Capstone-Team-3/open-fluency#25]
Practice Flashcards from Deck or Chapter - Shows only the first card in custom deck
Location: Deck Search -> select Deck -> Practice Flashcards. Also Search Chapter
1) The Practice page shows only the first card in the Deck/Chapter. There is no way to move forward or back through the deck to see the other cards. This is a problem only for decks that are created by the user - Practice operation works fine for the system-provided decks/chapters created during the program startup.

**Comment by kalongthewires** [comment]
I can't reproduce this. Not sure if this was in some interim step when someone was making changes to decks (?)

**Comment by marcsolomon** [comment]
Problem is only with custom decks.  Problem description modified above.

**Comment by marcsolomon** [comment]
Still a problem. I didn't mean to close it earlier - the "close" button is too convenient.

**Comment by kalongthewires** [comment]
Aha - I fixed it - let me know if you see any additional issues with this.
