### ISSUE TITLE
Practice Flashcards from Courses shows only the first Flashcard

### ISSUE THREAD

**Issue by marcsolomon** [Capstone-Team-3/open-fluency#29]
This looks like the same glitch that Practice Flashcards from Decks had earlier today, that Kim so handily corrected
Only the first Flashcard in the opened Chapter is displayed. 
Also, the "Show Meaning" control is not displayed

**Comment by kalongthewires** [comment]
I wasn't seeing the problem with pagination for the Courses, but I applied the same fixes (my bad, should have done that earlier when I was fixing decks!). Let me know if you're still seeing this.
