### ISSUE TITLE
Language proficiencies on Sign Up page needs usability improvement. Unclear that can add many language proficiencies and that this is a required field. If Add button clicked too many times accidentally, cannot remove the extra panels.

### ISSUE THREAD

**Issue by kalongthewires** [Capstone-Team-3/open-fluency#3]

**Comment by marcsolomon** [comment]
sign up page - require native language
impact: low
location: sign up page
if you click Sign Up without specifying a Language Proficiency, the User Type field then is set blank and becomes unresponsive. you are unable to complete the sign up sequence
possible solution: new required dropdown for "Native Language" with provided default

**Comment by nicoten** [comment]
I implemented as Marc suggested. Added Remove button.
