### ISSUE TITLE
Cannot create Flashcard on Deck - Error 500

### ISSUE THREAD

**Issue by marcsolomon** [Capstone-Team-3/open-fluency#30]
Is this stuff you're working on Ben?
I did a pull of the code at about 9:00 this evening (Tue)
Location: Deck -> Flashcard Search -> Create Flashcard -> Create It
Error 500: Internal Server Error
URI /OpenFluency/flashcard/save
Class groovy.lang.MissingMethodException
Message
No signature of method: com.openfluency.media.MediaService.createAudio() is applicable for argument types: (java.lang.String, java.lang.String) values: [, 8] Possible solutions: createAudio(java.lang.String, [Ljava.lang.Byte;, java.lang.String), createImage(java.lang.String, java.lang.String)

**Comment by beacrett** [comment]
fixed
