### ISSUE TITLE
Increase size of flashcards (UI)

### ISSUE THREAD

**Issue by nicoten** [Capstone-Team-3/open-fluency#47]

**Comment by kalongthewires** [comment]
Can you clarify this - how big did he want them? What was the issue - the font size? Why exactly did he think they should be larger?

**Comment by nicoten** [comment]
He said that the symbol itself was too small. I increased the font a little but I think when viewing a single flashcard the symbol should be HUGE since we have tons of space, lots of whitespace to cover!
