### ISSUE TITLE
In flashcard customization panel: convert "Remove Current Customizations" button to a "Reset" button and separate "Remove images from card" and "Remove audio from card" (or similar) buttons

### ISSUE THREAD

**Issue by kalongthewires** [Capstone-Team-3/open-fluency#56]

**Comment by beacrett** [comment]
The way customization works right now, if you set a customization with no image url, then it will revert to the native image (or none if that was the native setting).  Same with Audio.  Are you suggesting we give the option to block out the native audio or image?

**Comment by kalongthewires** [comment]
What if the user customizes the audio and then wants to remove just the audio file they added without removing their custom image?

**Comment by kalongthewires** [comment]
I think the remove customizations button is sufficient. Closing.
