### ISSUE TITLE
Add in breadcrumbs (per UI wireframes) for better usability.

### ISSUE THREAD

**Issue by kalongthewires** [Capstone-Team-3/open-fluency#7]

**Comment by Keren249** [comment]
Add in breadcrumbs for course/chapter show and search.

**Comment by kalongthewires** [comment]
When logged in as a student, on "Enrolled Courses" page, the breadcrumbs should say "Enrolled Courses" instead of "My courses".

**Comment by Keren249** [comment]
Changed to "Enrolled Courses".

**Comment by nicoten** [comment]
Also need to add breadcrumbs in Practice Flashcards view, so the user can return to the Deck.
