### ISSUE TITLE
Illegal pattern 'Y' error on quiz/show and instructor dashboard

### ISSUE THREAD

**Issue by Keren249** [Capstone-Team-3/open-fluency#79]

**Comment by kalongthewires** [comment]
If you go to My Courses, choose a course and then click "Add Quiz" and then create a new quiz, the quiz/show page appears to work. Can you tell me what you're seeing?

**Comment by Keren249** [comment]
I just tried this path Add Quiz-> Create -> and then I got this error on the quiz/show page:
URI : /OpenFluency/quiz/show/3
Class: java.lang.IllegalArgumentException
Message : Illegal pattern character 'Y'

**Comment by kalongthewires** [comment]
Hm. Not sure what's happening! That path works for me.
